### ISSUE TITLE
`ImportError`: cannot import name 'V1CloudSpaceAppAction' from 'lightning_cloud.openapi.models' 

### ISSUE THREAD

**Issue by ordabayevy** [Lightning-AI/lightning#18777]
### Bug description

`ImportError` upon importing `lightning.pytorch` (full error message below). This happens during the Github Actions CI which uses the latest available version of lightning through pip. The code used to work before on Github Actions.

### What version are you seeing the problem on?

master

### How to reproduce the bug

```python
import lightning.pytorch as pl
```

### Error messages and logs

```
cellarium/ml/data/dadc_datamodule.py:6: in <module>
    import lightning.pytorch as pl
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/lightning/__init__.py:17: in <module>
    from lightning.app import storage  # noqa: E402
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/lightning/app/__init__.py:37: in <module>
    from lightning.app.plugin.plugin import LightningPlugin  # noqa: E402
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/lightning/app/plugin/__init__.py:1: in <module>
    import lightning.app.plugin.actions as actions
/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/lightning/app/plugin/actions.py:18: in <module>
    from lightning_cloud.openapi.models import V1CloudSpaceAppAction, V1CloudSpaceAppActionType
E   ImportError: cannot import name 'V1CloudSpaceAppAction' from 'lightning_cloud.openapi.models' 
```

### Environment

<details>
  <summary>Current environment</summary>

```
#- Lightning Component (e.g. Trainer, LightningModule, LightningApp, LightningWork, LightningFlow):
#- PyTorch Lightning Version (e.g., 1.5.0):
#- Lightning App Version (e.g., 0.5.2):
#- PyTorch Version (e.g., 2.0):
#- Python version (e.g., 3.9):
#- OS (e.g., Linux):
#- CUDA/cuDNN version:
#- GPU models and configuration:
#- How you installed Lightning(`conda`, `pip`, source):
#- Running environment of LightningApp (e.g. local, cloud):
```

</details>

**Comment by lantiga** [comment]
Thank you @ordabayevy can you try again now? We had a transient problem on PyPI and it should be fixed now.

**Comment by ordabayevy** [comment]
It's fixed now. Thanks @lantiga !

**Comment by jkooy** [comment]
Same bug here. This one is not fixed. 
Adding this PR works. https://github.com/Lightning-AI/lightning/pull/18778/files
